# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' compute a baseflow time series using the Lyne & Hollick algorithm.
#' 
#' This function compute baseflow time series using the algorithm of Lyne and Hollick
#' (1979)
#' 
#' @param Q numeric vector. Streamflow vector.
#' @param k float. parameter.
#' @return Returns a baseflow time series.
#' @references 
#' V. Lyne and M. Hollick,
#' “Stochastic time-variable rainfall-runoff modelling,”
#' in Hydrology and Water Ressources Symposium, Perth, Australia, 1979, pp. 89–92.
#' @export
baseflow_LyneHollick <- function(Q, k) {
    .Call('_HSA_baseflow_LyneHollick', PACKAGE = 'HSA', Q, k)
}

#' compute a baseflow time series using the Chapman & Maxwell algorithm.
#' 
#' This function compute baseflow time series using the algorithm of Chapman and Maxwell
#' (1996)
#' 
#' @param Q numeric vector. Streamflow vector.
#' @param k float. parameter.
#' @return Returns a baseflow time series.
#' @references 
#' T. G. Chapman and A. I. Maxwell, 
#' “Baseflow separation - comparison of numerical methods with tracer experiments,” Hobart, Tasmania, 1996.
#' @export
baseflow_ChapmanMaxwell <- function(Q, k) {
    .Call('_HSA_baseflow_ChapmanMaxwell', PACKAGE = 'HSA', Q, k)
}

#' compute a baseflow time series using the Boughton algorithm.
#' 
#' This function compute baseflow time series using the algorithm of Boughton
#' described in Chapman (1999)
#' 
#' @param Q numeric vector. Streamflow vector.
#' @param k float. parameter.
#' @param C float. parameter.
#' @return Returns a baseflow time series.
#' @references 
#' T. Chapman,
#' “A comparison of algorithms for streamflow recession and basefow separation,”
#' Hydrological Processes, vol. 13, pp. 701–714, 1999.
#' @export
baseflow_Boughton <- function(Q, k, C) {
    .Call('_HSA_baseflow_Boughton', PACKAGE = 'HSA', Q, k, C)
}

#' compute a baseflow time series using the Eckhardt algorithm.
#' 
#' This function compute baseflow time series using the algorithm of Eckhardt (2005, 2008)
#' 
#' @param Q numeric vector. Streamflow vector.
#' @param a float. parameter.
#' @param BFImax float. parameter.
#' @return Returns a baseflow time series.
#' @references 
#'b K. Eckhardt,
#' “How to construct recursive digital filters for baseflow separation,” 
#' Hydrological Processes, vol. 19, pp. 507–515, 2005.
#' K. Eckhardt, 
#' “A comparison of baseflow indices, which were calculated with seven different baseflow separation methods,”
#' Journal of Hydrology, vol. 352, pp. 168–173, 2008, doi: 10.1016/j.jhydrol.2008.01.005.
#' @export
baseflow_Eckhardt <- function(Q, a, BFImax) {
    .Call('_HSA_baseflow_Eckhardt', PACKAGE = 'HSA', Q, a, BFImax)
}

ioh_min_pivots <- function(Q, d, k) {
    .Call('_HSA_ioh_min_pivots', PACKAGE = 'HSA', Q, d, k)
}

rec_events <- function(imax, imin) {
    .Call('_HSA_rec_events', PACKAGE = 'HSA', imax, imin)
}

